on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-library:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    concurrency: ci-${{github.ref}}

    steps:
      - name: Checkout to repo in current branch
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Build Library
        run: npm run build

  # Deployment job
  deploy-library:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-22.04
    needs: build-library
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout to repo in current branch
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Build Library
        run: npm run build

      - name: Deploy to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
